import Head from 'next/head'
import HomePage from './HomePage'
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation';
import Login from '@/components/Authentication/Login';
import Register from '@/components/Authentication/Register';
import { useGlobalContext } from '@/context/context';

export default function Home() {
  const {isLoggedIn, isRegistered} = useGlobalContext();
  return (
    <>
    <Head>
        <title>Shorten-Link App</title>
        <meta name="description" content="Generated by hcue66" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="container mx-auto">
      <Navigation/>
      <HomePage/>
      {isLoggedIn && <Login/>}
      {isRegistered && <Register/>}
     
   
    </main>
    
    <Footer/>
    </>
  )
}
