import Head from 'next/head'
import HomePage from './HomePage'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
    <Head>
        <title>Shorten-Link App</title>
        <meta name="description" content="Generated by hcue66" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="text-center mainBackground">
      <HomePage/>
    </main>
    <Footer/>
    </>
  )
}
